apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3
spec:
  parallelism: 1
  completions: 2
  template:
    metadata:
      name: iperf-client3
    spec:
      containers:
      - name: iperf-client-container3
        image: networkstatic/iperf3
        args: ["-c" , "10.106.170.103", "-n", "80G"]
      restartPolicy: Never
      nodeSelector: 
        color: red
