apiVersion: apps/v1 # docker run  -it --rm --name=iperf3-server -p 5201:5201 networkstatic/iperf3 -s
kind: Deployment
metadata:
  name: iperf-deployment
  labels:
    app: iperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf
  template:
    metadata:
      labels:
        app: iperf
    spec:
      containers:
      - name: iperf-server
        image: networkstatic/iperf3:latest
        ports: 
        - containerPort: 5201
        args: ["-s"]
